// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.19;

/**
 * @title Verifier
 * @dev Contract for verifying Groth16 proofs (generated by snarkjs)
 */
contract Verifier {
    // ============ Structures ============

    struct VerifyingKey {
        Pairing.G1Point alfa1;
        Pairing.G2Point beta2;
        Pairing.G2Point gamma2;
        Pairing.G2Point delta2;
        Pairing.G1Point[] IC;
    }

    struct Proof {
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }

    // ============ Pairing Library ============

    library Pairing {
        struct G1Point {
            uint256 X;
            uint256 Y;
        }

        struct G2Point {
            uint256[2] X;
            uint256[2] Y;
        }

        function P1() internal pure returns (G1Point memory) {
            return G1Point(1, 2);
        }

        function P2() internal pure returns (G2Point memory) {
            return
                G2Point(
                    [
                        11559732032986387107991004021392285783925812861821192530917403151452391805634,
                        10857046999023057135944570762232829481370756359578518086990519993285655852781
                    ],
                    [
                        4082367875863433681332203403145435568316851327593401208105741076214120093531,
                        8495653923123431417604973247489272438418190587263600148770280649306958101930
                    ]
                );
        }

        function negate(G1Point memory p)
            internal
            pure
            returns (G1Point memory r)
        {
            uint256 q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
            if (p.X == 0 && p.Y == 0) return G1Point(0, 0);
            return G1Point(p.X, q - (p.Y % q));
        }

        function addition(G1Point memory p1, G1Point memory p2)
            internal
            view
            returns (G1Point memory r)
        {
            uint256[4] memory input;
            input[0] = p1.X;
            input[1] = p1.Y;
            input[2] = p2.X;
            input[3] = p2.Y;
            bool success;
            assembly {
                success := staticcall(sub(gas(), 2000), 6, input, 0xc0, r, 0x60)
            }
            require(success, "Addition failed");
        }

        function scalar_mul(G1Point memory p, uint256 s)
            internal
            view
            returns (G1Point memory r)
        {
            uint256[3] memory input;
            input[0] = p.X;
            input[1] = p.Y;
            input[2] = s;
            bool success;
            assembly {
                success := staticcall(sub(gas(), 2000), 7, input, 0x80, r, 0x60)
            }
            require(success, "Scalar multiplication failed");
        }

        function pairing(G1Point[] memory p1, G2Point[] memory p2)
            internal
            view
            returns (bool)
        {
            require(p1.length == p2.length, "Pairing length mismatch");
            uint256 elements = p1.length;
            uint256 inputSize = elements * 6;
            uint256[] memory input = new uint256[](inputSize);

            for (uint256 i = 0; i < elements; i++) {
                input[i * 6 + 0] = p1[i].X;
                input[i * 6 + 1] = p1[i].Y;
                input[i * 6 + 2] = p2[i].X[0];
                input[i * 6 + 3] = p2[i].X[1];
                input[i * 6 + 4] = p2[i].Y[0];
                input[i * 6 + 5] = p2[i].Y[1];
            }

            uint256[1] memory out;
            bool success;
            assembly {
                success := staticcall(
                    sub(gas(), 2000),
                    8,
                    add(input, 0x20),
                    mul(inputSize, 0x20),
                    out,
                    0x20
                )
            }
            require(success, "Pairing check failed");
            return out[0] != 0;
        }

        function pairingProd2(
            G1Point memory a1,
            G2Point memory a2,
            G1Point memory b1,
            G2Point memory b2
        ) internal view returns (bool) {
            G1Point[] memory p1 = new G1Point[](2);
            G2Point[] memory p2 = new G2Point[](2);
            p1[0] = a1;
            p1[1] = b1;
            p2[0] = a2;
            p2[1] = b2;
            return pairing(p1, p2);
        }

        function pairingProd4(
            G1Point memory a1,
            G2Point memory a2,
            G1Point memory b1,
            G2Point memory b2,
            G1Point memory c1,
            G2Point memory c2,
            G1Point memory d1,
            G2Point memory d2
        ) internal view returns (bool) {
            G1Point[] memory p1 = new G1Point[](4);
            G2Point[] memory p2 = new G2Point[](4);
            p1[0] = a1;
            p1[1] = b1;
            p1[2] = c1;
            p1[3] = d1;
            p2[0] = a2;
            p2[1] = b2;
            p2[2] = c2;
            p2[3] = d2;
            return pairing(p1, p2);
        }
    }

    // ============ Verification Functions ============

    function verifyingKey()
        internal
        pure
        returns (VerifyingKey memory vk)
    {
        vk.alfa1 = Pairing.G1Point(
            20491192015591948497716182087483528521948435271382556547557601032576341464587,
            9383485363053290200918347156157941711091682237326766378654104852147812181684
        );
        vk.beta2 = Pairing.G2Point(
            [
                4252822878758300859123897981450591353533073812691539160924896926969400612917,
                17825052563265134637141994154633673825931460629304068964184311476550918629696
            ],
            [
                13181128799624622580362835838789603953341521830289681925009968641371256235751,
                5571420556614711718798806913220457555790379993871246786409331490635088733359
            ]
        );
        vk.gamma2 = Pairing.G2Point(
            [
                11559732032986387107991004021392285783925812861821192530917403151452391805634,
                10857046999023057135944570762232829481370756359578518086990519993285655852781
            ],
            [
                4082367875863433681332203403145435568316851327593401208105741076214120093531,
                8495653923123431417604973247489272438418190587263600148770280649306958101930
            ]
        );
        vk.delta2 = Pairing.G2Point(
            [
                11559732032986387107991004021392285783925812861821192530917403151452391805634,
                10857046999023057135944570762232829481370756359578518086990519993285655852781
            ],
            [
                4082367875863433681332203403145435568316851327593401208105741076214120093531,
                8495653923123431417604973247489272438418190587263600148770280649306958101930
            ]
        );
        vk.IC = new Pairing.G1Point[](8);
        vk.IC[0] = Pairing.G1Point(
            7687146299415959549404741521290209449330679025336055008093628805212845371215,
            5737437747499534071788620989358361792473994506502010507957710701524063442876
        );
        vk.IC[1] = Pairing.G1Point(
            11584110317297736491939437233462601391436635793598408922945112428903481881575,
            9424541332962386936491980418944285970193941054644899216668384992424528334390
        );
        vk.IC[2] = Pairing.G1Point(
            19788613035649084154212950503733457176714400087966103646768463103879123226126,
            5917482897781628384670191144699440046358122955650103438659224350634429980895
        );
        vk.IC[3] = Pairing.G1Point(
            12986652708531291845855810038856159116499935693650147490501698553025317195482,
            6853904027524644245243152237829820543579227210751996781367491255935730218299
        );
        vk.IC[4] = Pairing.G1Point(
            19517750467268446918767797736004254937894152938845618167359620607916136518669,
            15112819959472268598844493883247402701453575939048405241910302659440813483427
        );
        vk.IC[5] = Pairing.G1Point(
            370822263776051795224730173335074648373684155355981867116160915587839373316,
            13004925608871398898652345755232390391581317752003757064077468591130190263290
        );
        vk.IC[6] = Pairing.G1Point(
            8128970913679397249440397633307458580027980086779349699938890325442168244874,
            17917676079258098665685503041137175863890699949983421726462862890824162650817
        );
        vk.IC[7] = Pairing.G1Point(
            21317803290211340356165031602303454014459418931265703746231504346075070279329,
            1142263558365597148677940383937807713706654503522409964367615132564445474828
        );
    }

    function verify(
        uint256[] memory input,
        Proof memory proof
    ) internal view returns (uint256) {
        uint256 snark_scalar_field = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
        VerifyingKey memory vk = verifyingKey();
        require(input.length + 1 == vk.IC.length, "Verification key input length mismatch");

        Pairing.G1Point memory vk_x = Pairing.G1Point(0, 0);
        for (uint256 i = 0; i < input.length; i++) {
            require(
                input[i] < snark_scalar_field,
                "Verification key input out of range"
            );
            vk_x = Pairing.addition(
                vk_x,
                Pairing.scalar_mul(vk.IC[i + 1], input[i])
            );
        }
        vk_x = Pairing.addition(vk_x, vk.IC[0]);

        if (
            !Pairing.pairingProd4(
                Pairing.negate(proof.A),
                proof.B,
                vk.alfa1,
                vk.beta2,
                vk_x,
                vk.gamma2,
                proof.C,
                vk.delta2
            )
        ) return 1;
        return 0;
    }

    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[7] memory input
    ) public view returns (bool r) {
        Proof memory proof;
        proof.A = Pairing.G1Point(a[0], a[1]);
        proof.B = Pairing.G2Point(
            [b[0][0], b[0][1]],
            [b[1][0], b[1][1]]
        );
        proof.C = Pairing.G1Point(c[0], c[1]);

        uint256[] memory inputValues = new uint256[](input.length);
        for (uint256 i = 0; i < input.length; i++) {
            inputValues[i] = input[i];
        }

        if (verify(inputValues, proof) == 0) {
            return true;
        } else {
            return false;
        }
    }
}
